name: CD PIPELINE

on:
  workflow_run:
    workflows: ["CI PIPELINE"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      # LOGIN TO DOCKER HUB
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # PULL DOCKER IMAGE FROM DOCKER HUB
      - name: Docker Pull
        run: sudo docker pull rahul28112002/neochat-server:latest

      # REMOVE OLD CONTAINER
      - name: Remove Existing Container
        run: |
          sudo docker stop neochat-server-container || true
          sudo docker rm -f neochat-server-container || true

      # PRINT ENVIRONMENT VARIABLES
      - name: Print Environment Variables
        run: |
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}"
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}"
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}"
          echo "CRYPTR_SECRET=${{ secrets.CRYPTR_SECRET }}"
          echo "CLOUD_NAME=${{ secrets.CLOUD_NAME }}"
          echo "API_KEY=${{ secrets.API_KEY }}"
          echo "API_SECRET=${{ secrets.API_SECRET }}"
          echo "FOLDER_NAME=${{ secrets.FOLDER_NAME }}"
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}"
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}"
          echo "MAIL_USER=${{ secrets.MAIL_USER }}"
          echo "MAIL_PASS=${{ secrets.MAIL_PASS }}"

      # RUN NEW DOCKER CONTAINER
      - name: Run Docker Container
        run: |
          sudo docker run -d \
          -p "${{ secrets.PORT }}:${{ secrets.PORT }}" \
          --env "PORT=${{ secrets.PORT }}" \
          --env "DATABASE_URI=${{ secrets.DATABASE_URI }}" \
          --env "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
          --env "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" \
          --env "CRYPTR_SECRET=${{ secrets.CRYPTR_SECRET }}" \
          --env "CLOUD_NAME=${{ secrets.CLOUD_NAME }}" \
          --env "API_KEY=${{ secrets.API_KEY }}" \
          --env "API_SECRET=${{ secrets.API_SECRET }}" \
          --env "FOLDER_NAME=${{ secrets.FOLDER_NAME }}" \
          --env "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" \
          --env "MAIL_HOST=${{ secrets.MAIL_HOST }}" \
          --env "MAIL_USER=${{ secrets.MAIL_USER }}" \
          --env "MAIL_PASS=${{ secrets.MAIL_PASS }}" \
          --name neochat-server-container \
          rahul28112002/neochat-server:latest
