name: CI PIPELINE

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # CHECKOUT REPO CODE
      - uses: actions/checkout@v4

      # LOGIN TO DOCKER HUB
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # CREATE DOCKER IMAGE
      - name: Build the Docker image
        run: sudo docker build -t rahul28112002/neochat-server:latest ./server

      # PUSH DOCKER IMAGE TO DOCKER HUB
      - name: Docker Push
        run: docker push rahul28112002/neochat-server:latest

      # LOGOUT FROM DOCKER HUB
      - name: Logout from Docker Hub
        run: docker logout